#+TITLE:  Emacs Settings for Python
#+AUTHOR: Markus Sievers
#+EMAIL:  markussievers88@gmail.com
#+DATE:   [2016-06-02 Thu]
#+TAGS:   emacs python

I stole most of it from [[https://github.com/howardabrams/dot-files][Howard Abrams' dot-files]]. He said he stole his
Python package ideas from [[https://github.com/gabrielelanaro/emacs-for-python][Gabriel Elanaro's git project]]. As of right
now I will give the Jedi implementation a try...

* TODO Virtual Environments

  Virtual environments nicely solve the issue when you write a python
  program and make use of a certain module. If you then upgrade the
  included module your program may not work anymore. Virtual
  environments makes a local copy of all necessary python libraries
  preventing you from running into that problem.

  All development for Python is done in [[http://docs.python-guide.org/en/latest/dev/virtualenvs/][virtual environments]].
  However, this is a monstrous collection of layers, so I am now using
  [[https://github.com/yyuu/pyenv][pyenv]] for all my Pythonic virtualization needs, as it does a better
  job of both [[http://virtualenvwrapper.readthedocs.org/en/latest/index.html][virtualenvwrapper]] and [[https://github.com/kennethreitz/autoenv][autoenv]]. Since we are on Linux,
  let’s do it neckbeard-style:

  #+BEGIN_SRC sh
    git clone https://github.com/yyuu/pyenv.git ~/.pyenv
    git clone https://github.com/yyuu/pyenv-virtualenv.git ~/.pyenv/plugins/pyenv-virtualenv
  #+END_SRC

  Next, use pip to install virtualenv globally.

  #+BEGIN_SRC sh
    sudo pip install virtualenv
  #+END_SRC

  And use them by configuring our [[file:profile.org::*Python][.profile]].

  For a given /project/, we first install a particular Python version
  for it using the =pyenv= command (which must be done prior to
  starting a new virtual environment with the =mkvirtualenv= command):

  #+BEGIN_SRC sh
    pyenv install 3.5.1    # pyenv versions to see what is installed
  #+END_SRC

  Get path to this built/installed executable:

  #+BEGIN_SRC sh
    pyenv local 3.5.1
    pyenv which python
  #+END_SRC

  Each project (environment) will be *named*, and the version of
  Python can be specified based on the results of the =pyenv which=
  command above, for instance:

  #+BEGIN_SRC sh
    pyenv virtualenv 3.5.1 lab
  #+END_SRC

  And to use the environment in a shell, issue:

  #+BEGIN_SRC sh
    pyenv activate lab
  #+END_SRC

  Or, better yet, use the =local= option to make that environment
  active whenever you enter that directory:

  #+BEGIN_SRC sh
    pyenv local lab
  #+END_SRC

  Now, commands like =pip= should be isolated to that virtual environment
  as well as the needed version.

  The [[http://elpy.readthedocs.org/en/latest/concepts.html#virtual-envs][Elpy Project]] deals with the =virtualenvwrapper=, so call function,
  =M-x pyvenv-workon= to activate a virtual environment
  (see [[http://elpy.readthedocs.org/en/latest/concepts.html#virtual-envs][these instructions]]).

* Basics

  WSGI files are just Python files in disguise, so tell them to use
  the Python environment. Careful with the tabs, my friend.

  #+BEGIN_SRC elisp
    (use-package python
      :mode ("\\.py\\'" . python-mode)
      ("\\.wsgi$" . python-mode)
      :interpreter ("python3" . python-mode)

      :init
      (setq-default indent-tabs-mode nil)
      (setq-default py-python-command "python3")

      :config
      (setq python-indent 4)
      (add-hook 'python-mode-hook 'color-identifiers-mode))
  #+END_SRC

* Nose

  Unit test and code coverage tool for Python now comes to Emacs
  with [[http://ivory.idyll.org/articles/nose-intro.html][Python Nose]].

  #+BEGIN_SRC sh
    pip install nose
  #+END_SRC

  The ELPY project automatically adds support [[http://elpy.readthedocs.org/en/latest/ide.html#testing][for testing]].

* Jedi

  Auto-completion system for Python. This code hooks Jedi into the
  standard Python mode. See [[http://tkf.github.io/emacs-jedi/][these instructions]] for details (but this
  should have been installed for Elpy).

  #+BEGIN_SRC sh
    pip install jedi
  #+END_SRC

* Anaconda

  While [[https://github.com/jorgenschaefer/elpy/wiki][ELPY]] tries to be the all-in-one Python IDE, [[https://github.com/proofit404/anaconda-mode][Anaconda]] is
  thinner wrapper around Jedi, which seems to work a bit better for me
  and the fact that I need to use =pyenv= (instead of =pyvenv=).

  #+BEGIN_SRC elisp :tangle no
    (use-package anaconda-mode
      :ensure t
      :init (add-hook 'python-mode-hook 'anaconda-mode)
            (add-hook 'python-mode-hook 'anaconda-eldoc-mode)
      :config (use-package company-anaconda
                :ensure t
                :init (add-hook 'python-mode-hook 'anaconda-mode)
                (eval-after-load "company"
                  '(add-to-list 'company-backends '(company-anaconda :with company-capf)))))
  #+END_SRC

  Oh, make sure we have [[https://github.com/proofit404/company-anaconda][Company-Anaconda]] configured too.

* ELPY

  According to the [[https://github.com/jorgenschaefer/elpy/wiki][ELPY Web Site]], we first install the python-based
  package components:

  #+BEGIN_SRC sh
    # and importmagic for automatic imports
    pip install importmagic
    pip install elpy
  #+END_SRC

  Once this has been installed, we can enable it:

  #+BEGIN_SRC elisp
    (use-package elpy
      :ensure t
      :commands elpy-enable
      :init (with-eval-after-load 'python (elpy-enable))

      :config
      (electric-indent-local-mode -1)
      (delete 'elpy-module-highlight-indentation elpy-modules)
      (delete 'elpy-module-flymake elpy-modules)

      (defun ms/elpy-goto-definition ()
        (interactive)
        (condition-case err
          (elpy-goto-definition)
          ('error (find-tag (symbol-name (symbol-at-point))))))

      :bind (:map elpy-mode-map ([remap elpy-goto-definition] . ms/elpy-goto-definition)))
  #+END_SRC

  Since ELPY is not a simple mode, but a collection of smaller modes
  stitched together, we have to call ~with-eval-after-load~ (see [[http://emacs.stackexchange.com/questions/10065/how-can-i-defer-loading-elpy-using-use-package][this discussion]])

  See [[http://elpy.readthedocs.org/en/latest/ide.html][the documentation]] for details, but:
  - =C-c C-f= :: Find Python file
  - =C-c C-s= :: Grep for a Python symbol
  - =C-c C-z= :: Switch to the Python Shell
  - =C-c C-c= :: Send region to the Python interpreter

  Note: The elpy-goto-definition is nice and all if you have a full
  project with a running interpreter, but I want to use tags as a
  fallback.  However, since the function throws an error, I can't
  simply /advice/ the function, like:

  #+BEGIN_SRC elisp :tangle no
    (advice-add 'elpy-goto-definition :after-until 'find-tag)
  #+END_SRC

  Instead, I had to create a function wrapper.

* Temporary Error Fixes

  #+BEGIN_SRC elisp
    (when (eq system-type 'windows-nt)
      (setq python-shell-completion-native-enable nil))
  #+END_SRC

* Technical Artifacts

  Make sure that we can simply =require= this library.

  #+BEGIN_SRC elisp
    (provide 'init-python)
  #+END_SRC

  Before you can build this on a new system, make sure that you put
  the cursor over any of these properties, and hit: =C-c C-c=

#+DESCRIPTION: A literate programming version of my Emacs Initialization of Python
#+PROPERTY:    header-args :results silent
#+PROPERTY:    header-args+ :tangle ~/.emacs.d/elisp/init-python.el
#+PROPERTY:    header-args+ :eval no-export
#+PROPERTY:    header-args+ :comments org
#+PROPERTY:    header-args:sh :tangle no
#+OPTIONS:     num:nil toc:nil todo:nil tasks:nil tags:nil
#+OPTIONS:     skip:nil author:nil email:nil creator:nil timestamp:nil
#+INFOJS_OPT:  view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
