#+TITLE:  My Shell Dot Profile
#+AUTHOR: Markus Sievers
#+EMAIL:  markussievers88@gmail.com
#+DATE:   [2016-05-28 Sat]

This org file generates my =.profile=, which contains environment
variables, custom shell functions and similar settings.

* Path

   We want to add these directories, but only if they exist. This
   makes this more portable between my computers.

#+BEGIN_SRC sh
  OLDPATH=$PATH
  PATH=$HOME/bin

  for DIR in /opt/local/bin /opt/local/sbin /usr/local/bin /usr/local/sbin
  do
    if [ -d $DIR ]
    then
        PATH=$PATH:$DIR
    fi
  done

  PATH=$PATH:$OLDPATH
#+END_SRC


* Emacs

  Set =EDITOR= to start up an =emacsclient=, but do that from the one
  I built from Homebrew:

  #+BEGIN_SRC sh
    export ALTERNATE_EDITOR=/usr/bin/emacs
    export EDITOR=/usr/bin/emacsclient
  #+END_SRC



* Bashrc

  Most of my settings will be inside the =.bashrc= because that is more
  relevant to my work.  The following code will load those
  configurations. For some information on the load order check out
  this [[https://shreevatsa.wordpress.com/2008/03/30/zshbash-startup-files-loading-order-bashrc-zshrc-etc/][article]].
  
  #+BEGIN_SRC sh
    if [ -n "$BASH_VERSION" ]; then
        # include .bashrc if it exists
        if [ -f "$HOME/.bashrc" ]; then
            . "$HOME/.bashrc"
        fi
    fi
  #+END_SRC

* Prompt

  A helper function to help trim down lengthy directories:

  #+BEGIN_SRC sh
    function _trim_dir {
        V='[[:alnum:]._-]'
        D='[[:alnum:]._/-]'
        sed -E "s|/$D+/($V+)|../\1|; s/ / /g" <<< $1
    }
  #+END_SRC

  I wanna add everything to my command line prompt: the Git
  repository, the Python virtual environment (in white), the Ruby
  Virtual Environment (in red) ... of course, now I have no room to
  type commands. ;-)

  #+BEGIN_SRC sh
    export PS1='\[\e[1;34m\]$(prompt_dir)\[\e[1;32m\]$(_mygit_ps1)\[\e[0m\] \$ '

    if [ -d ~/.rvm ]
    then
        export PS1='\[\e[1;31m\]$(~/.rvm/bin/rvm-prompt v g)'"$PS1"
    fi
  #+END_SRC

  Good thing I seldom use a shell.


* Technical Gunk

  Anything else that is interesting, will be set up in more
  either more shell-specific files, or in [[file:sh-functions.org][Shell Functions]] file.
  The following are the tangled settings. Type: =C-c C-v t=
  to create the script file.

#+PROPERTY: tangle ~/.profile
#+PROPERTY: comments org
#+PROPERTY: shebang #!/bin/sh
#+DESCRIPTION: Global environment variables for all shells
